name: Direct Gradle Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Download and setup Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-8.4-bin.zip
        unzip gradle-8.4-bin.zip
        echo "GRADLE_HOME=$PWD/gradle-8.4" >> $GITHUB_ENV
        echo "$PWD/gradle-8.4/bin" >> $GITHUB_PATH
        
    - name: Verify files
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Gradle files:"
        ls -la *.gradle* || echo "No gradle files found"
        echo "App directory:"
        ls -la app/ || echo "No app directory found"
        
    - name: Build APK
      run: |
        gradle assembleDebug --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: douyin-automation-apk
        path: app/build/outputs/apk/debug/app-debug.apk
